// Vocabulary data — 5 TOEIC topics parsed from 5.topic.txt
const TOPICS = [
  {
    id: 1,
    name: 'Contracts',
    words: [
      { word: 'agreement', ipa: '/əˈɡriːmənt/', type: 'n', meaning: 'một thỏa thuận chung, một hợp đồng' },
      { word: 'party', ipa: '/ˈpɑːrti/', type: 'n', meaning: 'một người hoặc một nhóm tham gia vào một hợp đồng' },
      { word: 'provision', ipa: '/prəˈvɪʒn/', type: 'n', meaning: 'một điều kiện cụ thể trong hợp đồng' },
      { word: 'clause', ipa: '/klɔːz/', type: 'n', meaning: 'một phần trong hợp đồng' },
      { word: 'agree', ipa: '/əˈɡriː/', type: 'v', meaning: 'có cùng quan điểm hoặc sự hiểu biết' },
      { word: 'obligate', ipa: '/ˈɑːblɪɡeɪt/', type: 'v', meaning: 'ràng buộc về mặt pháp lý hoặc đạo đức' },
      { word: 'sign', ipa: '/saɪn/', type: 'v', meaning: 'viết tên của bạn vào một tài liệu để thể hiện sự chấp thuận' },
      { word: 'resolve', ipa: '/rɪˈzɑːlv/', type: 'v', meaning: 'để tìm một giải pháp' },
      { word: 'binding', ipa: '/ˈbaɪndɪŋ/', type: 'adj', meaning: 'yêu cầu về mặt pháp lý' },
      { word: 'contractual', ipa: '/kənˈtræktʃuəl/', type: 'adj', meaning: 'liên quan đến hợp đồng' },
      { word: 'legal', ipa: '/ˈliːɡl/', type: 'adj', meaning: 'được pháp luật cho phép' },
      { word: 'legally', ipa: '/ˈliːɡəli/', type: 'adv', meaning: 'theo cách được pháp luật cho phép' },
    ],
  },
  {
    id: 2,
    name: 'Marketing',
    words: [
      { word: 'market', ipa: '/ˈmɑːrkɪt/', type: 'n', meaning: 'nhu cầu về một sản phẩm' },
      { word: 'competition', ipa: '/ˌkɑːmpəˈtɪʃn/', type: 'n', meaning: 'hoạt động cạnh tranh' },
      { word: 'strategy', ipa: '/ˈstrætədʒi/', type: 'n', meaning: 'một kế hoạch hành động' },
      { word: 'customer', ipa: '/ˈkʌstəmər/', type: 'n', meaning: 'ai đó mua hàng hóa hoặc dịch vụ' },
      { word: 'advertise', ipa: '/ˈædvərtaɪz/', type: 'v', meaning: 'để quảng bá một sản phẩm hoặc dịch vụ' },
      { word: 'attract', ipa: '/əˈtrækt/', type: 'v', meaning: 'để rút ra bằng cách kháng cáo' },
      { word: 'consume', ipa: '/kənˈsuːm/', type: 'v', meaning: 'sử dụng hoặc mua một sản phẩm' },
      { word: 'market', ipa: '/ˈmɑːrkɪt/', type: 'v', meaning: 'để quảng bá và bán' },
      { word: 'effective', ipa: '/ɪˈfɛktɪv/', type: 'adj', meaning: 'thành công trong việc tạo ra một kết quả mong muốn' },
      { word: 'productive', ipa: '/prəˈdʌktɪv/', type: 'adj', meaning: 'có thể sản xuất số lượng lớn' },
      { word: 'persuasive', ipa: '/pərˈsweɪsɪv/', type: 'adj', meaning: 'giỏi thuyết phục người khác' },
      { word: 'efficiently', ipa: '/ɪˈfɪʃəntli/', type: 'adv', meaning: 'theo cách đạt được năng suất tối đa' },
    ],
  },
  {
    id: 3,
    name: 'Warranties',
    words: [
      { word: 'warranty', ipa: '/ˈwɔːrənti/', type: 'n', meaning: 'một sự đảm bảo' },
      { word: 'defect', ipa: '/ˈdiːfɛkt/', type: 'n', meaning: 'một lỗi hoặc sự không hoàn hảo' },
      { word: 'claim', ipa: '/kleɪm/', type: 'n', meaning: 'một nhu cầu cho một cái gì đó do' },
      { word: 'coverage', ipa: '/ˈkʌvərɪdʒ/', type: 'n', meaning: 'mức độ mà một cái gì đó được bảo hiểm' },
      { word: 'guarantee', ipa: '/ˌɡærənˈtiː/', type: 'v', meaning: 'cam kết về chất lượng sản phẩm' },
      { word: 'replace', ipa: '/rɪˈpleɪs/', type: 'v', meaning: 'thay thế' },
      { word: 'refund', ipa: '/ˈriːfʌnd/', type: 'v', meaning: 'trả lại tiền' },
      { word: 'repair', ipa: '/rɪˈpɛr/', type: 'v', meaning: 'để sửa chữa hoặc khôi phục' },
      { word: 'defective', ipa: '/dɪˈfɛktɪv/', type: 'adj', meaning: 'có lỗi' },
      { word: 'valid', ipa: '/ˈvælɪd/', type: 'adj', meaning: 'được chấp nhận về mặt pháp lý' },
      { word: 'expired', ipa: '/ɪkˈspaɪərd/', type: 'adj', meaning: 'không còn hiệu lực' },
      { word: 'promptly', ipa: '/ˈprɑːmptli/', type: 'adv', meaning: 'không chậm trễ' },
    ],
  },
  {
    id: 4,
    name: 'Business Planning',
    words: [
      { word: 'goal', ipa: '/ɡoʊl/', type: 'n', meaning: 'một mục tiêu hoặc kết quả mong muốn' },
      { word: 'strategy', ipa: '/ˈstrætədʒi/', type: 'n', meaning: 'một kế hoạch hành động' },
      { word: 'forecast', ipa: '/ˈfɔːrkæst/', type: 'n', meaning: 'một dự đoán' },
      { word: 'resource', ipa: '/ˈriːsɔːrs/', type: 'n', meaning: 'một cổ phiếu hoặc nguồn cung cấp' },
      { word: 'forecast', ipa: '/ˈfɔːrkæst/', type: 'v', meaning: 'để dự đoán tương lai' },
      { word: 'plan', ipa: '/plæn/', type: 'v', meaning: 'quyết định và sắp xếp' },
      { word: 'analyze', ipa: '/ˈænəlaɪz/', type: 'v', meaning: 'để kiểm tra chi tiết' },
      { word: 'assess', ipa: '/əˈsɛs/', type: 'v', meaning: 'để đánh giá hoặc ước tính' },
      { word: 'strategic', ipa: '/strəˈtiːdʒɪk/', type: 'adj', meaning: 'liên quan đến kế hoạch dài hạn' },
      { word: 'realistic', ipa: '/ˌriːəˈlɪstɪk/', type: 'adj', meaning: 'thực tế và có thể đạt được' },
      { word: 'achievable', ipa: '/əˈtʃiːvəbl/', type: 'adj', meaning: 'có khả năng thực hiện được' },
      { word: 'effectively', ipa: '/ɪˈfɛktɪvli/', type: 'adv', meaning: 'theo cách đạt được kết quả mong muốn' },
    ],
  },
  {
    id: 5,
    name: 'Conferences',
    words: [
      { word: 'attendee', ipa: '/əˌtɛnˈdiː/', type: 'n', meaning: 'một người tham dự một cuộc họp' },
      { word: 'schedule', ipa: '/ˈskɛdʒuːl/', type: 'n', meaning: 'kế hoạch sự kiện' },
      { word: 'location', ipa: '/loʊˈkeɪʃn/', type: 'n', meaning: 'một địa điểm hoặc vị trí' },
      { word: 'venue', ipa: '/ˈvɛnjuː/', type: 'n', meaning: 'nơi diễn ra sự kiện' },
      { word: 'arrange', ipa: '/əˈreɪndʒ/', type: 'v', meaning: 'lập kế hoạch và tổ chức' },
      { word: 'hold', ipa: '/hoʊld/', type: 'v', meaning: 'tổ chức hoặc tiến hành' },
      { word: 'participate', ipa: '/pɑːrˈtɪsɪpeɪt/', type: 'v', meaning: 'tham gia' },
      { word: 'register', ipa: '/ˈrɛdʒɪstər/', type: 'v', meaning: 'để ghi danh hoặc đăng ký' },
      { word: 'convenient', ipa: '/kənˈviːniənt/', type: 'adj', meaning: 'phù hợp tốt với nhu cầu của một người' },
      { word: 'scheduled', ipa: '/ˈskɛdʒuːld/', type: 'adj', meaning: 'lên kế hoạch hoặc sắp xếp cho' },
      { word: 'confirmed', ipa: '/kənˈfɜːrmd/', type: 'adj', meaning: 'được thành lập hoặc xác minh' },
      { word: 'international', ipa: '/ˌɪntəˈnæʃnəl/', type: 'adj', meaning: 'quốc tế' },
    ],
  },
];
