// Nhãn từ loại đầy đủ bằng tiếng Việt (dùng cho mặt sau thẻ và tooltip)
const TYPE_LABELS = {
  n:   'Danh từ',
  v:   'Động từ',
  adj: 'Tính từ',
  adv: 'Trạng từ',
};

// Vocabulary data — 5 TOEIC topics + các chủ đề đời sống theo từng loại
const TOPICS = [
  {
    id: 1,
    name: 'Contracts',
    words: [
      { index: 1,  word: 'agreement',   ipa: '/əˈɡriːmənt/',      type: 'n',   meaning: 'một thỏa thuận chung, một hợp đồng' },
      { index: 2,  word: 'party',       ipa: '/ˈpɑːrti/',          type: 'n',   meaning: 'một người hoặc một nhóm tham gia vào một hợp đồng' },
      { index: 3,  word: 'provision',   ipa: '/prəˈvɪʒn/',         type: 'n',   meaning: 'một điều kiện cụ thể trong hợp đồng' },
      { index: 4,  word: 'clause',      ipa: '/klɔːz/',            type: 'n',   meaning: 'một phần trong hợp đồng' },
      { index: 5,  word: 'agree',       ipa: '/əˈɡriː/',           type: 'v',   meaning: 'có cùng quan điểm hoặc sự hiểu biết' },
      { index: 6,  word: 'obligate',    ipa: '/ˈɑːblɪɡeɪt/',      type: 'v',   meaning: 'ràng buộc về mặt pháp lý hoặc đạo đức' },
      { index: 7,  word: 'sign',        ipa: '/saɪn/',             type: 'v',   meaning: 'viết tên của bạn vào một tài liệu để thể hiện sự chấp thuận' },
      { index: 8,  word: 'resolve',     ipa: '/rɪˈzɑːlv/',        type: 'v',   meaning: 'để tìm một giải pháp' },
      { index: 9,  word: 'binding',     ipa: '/ˈbaɪndɪŋ/',        type: 'adj', meaning: 'yêu cầu về mặt pháp lý' },
      { index: 10, word: 'contractual', ipa: '/kənˈtræktʃuəl/',   type: 'adj', meaning: 'liên quan đến hợp đồng' },
      { index: 11, word: 'legal',       ipa: '/ˈliːɡl/',           type: 'adj', meaning: 'được pháp luật cho phép' },
      { index: 12, word: 'legally',     ipa: '/ˈliːɡəli/',         type: 'adv', meaning: 'theo cách được pháp luật cho phép' },
    ],
  },
  {
    id: 2,
    name: 'Marketing',
    words: [
      { index: 13, word: 'market',      ipa: '/ˈmɑːrkɪt/',        type: 'n',   meaning: 'nhu cầu về một sản phẩm' },
      { index: 14, word: 'competition', ipa: '/ˌkɑːmpəˈtɪʃn/',   type: 'n',   meaning: 'hoạt động cạnh tranh' },
      { index: 15, word: 'strategy',    ipa: '/ˈstrætədʒi/',      type: 'n',   meaning: 'một kế hoạch hành động' },
      { index: 16, word: 'customer',    ipa: '/ˈkʌstəmər/',       type: 'n',   meaning: 'ai đó mua hàng hóa hoặc dịch vụ' },
      { index: 17, word: 'advertise',   ipa: '/ˈædvərtaɪz/',      type: 'v',   meaning: 'để quảng bá một sản phẩm hoặc dịch vụ' },
      { index: 18, word: 'attract',     ipa: '/əˈtrækt/',          type: 'v',   meaning: 'để rút ra bằng cách kháng cáo' },
      { index: 19, word: 'consume',     ipa: '/kənˈsuːm/',         type: 'v',   meaning: 'sử dụng hoặc mua một sản phẩm' },
      { index: 20, word: 'promote',     ipa: '/prəˈmoʊt/',         type: 'v',   meaning: 'để quảng bá và bán' },
      { index: 21, word: 'effective',   ipa: '/ɪˈfɛktɪv/',        type: 'adj', meaning: 'thành công trong việc tạo ra một kết quả mong muốn' },
      { index: 22, word: 'productive',  ipa: '/prəˈdʌktɪv/',      type: 'adj', meaning: 'có thể sản xuất số lượng lớn' },
      { index: 23, word: 'persuasive',  ipa: '/pərˈsweɪsɪv/',     type: 'adj', meaning: 'giỏi thuyết phục người khác' },
      { index: 24, word: 'efficiently', ipa: '/ɪˈfɪʃəntli/',      type: 'adv', meaning: 'theo cách đạt được năng suất tối đa' },
    ],
  },
  {
    id: 3,
    name: 'Warranties',
    words: [
      { index: 25, word: 'warranty',    ipa: '/ˈwɔːrənti/',       type: 'n',   meaning: 'một sự đảm bảo' },
      { index: 26, word: 'defect',      ipa: '/ˈdiːfɛkt/',        type: 'n',   meaning: 'một lỗi hoặc sự không hoàn hảo' },
      { index: 27, word: 'claim',       ipa: '/kleɪm/',            type: 'n',   meaning: 'một nhu cầu cho một cái gì đó do' },
      { index: 28, word: 'coverage',    ipa: '/ˈkʌvərɪdʒ/',       type: 'n',   meaning: 'mức độ mà một cái gì đó được bảo hiểm' },
      { index: 29, word: 'guarantee',   ipa: '/ˌɡærənˈtiː/',      type: 'v',   meaning: 'cam kết về chất lượng sản phẩm' },
      { index: 30, word: 'replace',     ipa: '/rɪˈpleɪs/',        type: 'v',   meaning: 'thay thế' },
      { index: 31, word: 'refund',      ipa: '/ˈriːfʌnd/',        type: 'v',   meaning: 'trả lại tiền' },
      { index: 32, word: 'repair',      ipa: '/rɪˈpɛr/',          type: 'v',   meaning: 'để sửa chữa hoặc khôi phục' },
      { index: 33, word: 'defective',   ipa: '/dɪˈfɛktɪv/',      type: 'adj', meaning: 'có lỗi' },
      { index: 34, word: 'valid',       ipa: '/ˈvælɪd/',          type: 'adj', meaning: 'được chấp nhận về mặt pháp lý' },
      { index: 35, word: 'expired',     ipa: '/ɪkˈspaɪərd/',      type: 'adj', meaning: 'không còn hiệu lực' },
      { index: 36, word: 'promptly',    ipa: '/ˈprɑːmptli/',      type: 'adv', meaning: 'không chậm trễ' },
    ],
  },
  {
    id: 4,
    name: 'Business Planning',
    words: [
      { index: 37, word: 'goal',        ipa: '/ɡoʊl/',            type: 'n',   meaning: 'một mục tiêu hoặc kết quả mong muốn' },
      { index: 38, word: 'strategy',    ipa: '/ˈstrætədʒi/',      type: 'n',   meaning: 'một kế hoạch hành động' },
      { index: 39, word: 'forecast',    ipa: '/ˈfɔːrkæst/',       type: 'n',   meaning: 'một dự đoán' },
      { index: 40, word: 'resource',    ipa: '/ˈriːsɔːrs/',       type: 'n',   meaning: 'một cổ phiếu hoặc nguồn cung cấp' },
      { index: 41, word: 'predict',     ipa: '/prɪˈdɪkt/',        type: 'v',   meaning: 'để dự đoán tương lai' },
      { index: 42, word: 'plan',        ipa: '/plæn/',             type: 'v',   meaning: 'quyết định và sắp xếp' },
      { index: 43, word: 'analyze',     ipa: '/ˈænəlaɪz/',        type: 'v',   meaning: 'để kiểm tra chi tiết' },
      { index: 44, word: 'assess',      ipa: '/əˈsɛs/',           type: 'v',   meaning: 'để đánh giá hoặc ước tính' },
      { index: 45, word: 'strategic',   ipa: '/strəˈtiːdʒɪk/',   type: 'adj', meaning: 'liên quan đến kế hoạch dài hạn' },
      { index: 46, word: 'realistic',   ipa: '/ˌriːəˈlɪstɪk/',   type: 'adj', meaning: 'thực tế và có thể đạt được' },
      { index: 47, word: 'achievable',  ipa: '/əˈtʃiːvəbl/',     type: 'adj', meaning: 'có khả năng thực hiện được' },
      { index: 48, word: 'effectively', ipa: '/ɪˈfɛktɪvli/',     type: 'adv', meaning: 'theo cách đạt được kết quả mong muốn' },
    ],
  },
  {
    id: 5,
    name: 'Conferences',
    words: [
      { index: 49, word: 'attendee',     ipa: '/əˌtɛnˈdiː/',      type: 'n',   meaning: 'một người tham dự một cuộc họp' },
      { index: 50, word: 'schedule',     ipa: '/ˈskɛdʒuːl/',      type: 'n',   meaning: 'kế hoạch sự kiện' },
      { index: 51, word: 'location',     ipa: '/loʊˈkeɪʃn/',      type: 'n',   meaning: 'một địa điểm hoặc vị trí' },
      { index: 52, word: 'venue',        ipa: '/ˈvɛnjuː/',         type: 'n',   meaning: 'nơi diễn ra sự kiện' },
      { index: 53, word: 'arrange',      ipa: '/əˈreɪndʒ/',        type: 'v',   meaning: 'lập kế hoạch và tổ chức' },
      { index: 54, word: 'hold',         ipa: '/hoʊld/',           type: 'v',   meaning: 'tổ chức hoặc tiến hành' },
      { index: 55, word: 'participate',  ipa: '/pɑːrˈtɪsɪpeɪt/', type: 'v',   meaning: 'tham gia' },
      { index: 56, word: 'register',     ipa: '/ˈrɛdʒɪstər/',     type: 'v',   meaning: 'để ghi danh hoặc đăng ký' },
      { index: 57, word: 'convenient',   ipa: '/kənˈviːniənt/',   type: 'adj', meaning: 'phù hợp tốt với nhu cầu của một người' },
      { index: 58, word: 'scheduled',    ipa: '/ˈskɛdʒuːld/',     type: 'adj', meaning: 'lên kế hoạch hoặc sắp xếp cho' },
      { index: 59, word: 'confirmed',    ipa: '/kənˈfɜːrmd/',     type: 'adj', meaning: 'được thành lập hoặc xác minh' },
      { index: 60, word: 'international',ipa: '/ˌɪntəˈnæʃnəl/',  type: 'adj', meaning: 'quốc tế' },
    ],
  },
  {
    id: 6,
    name: 'Nghề nghiệp',
    words: [
      { index: 61, word: 'doctor',      ipa: '/ˈdɑːktər/',        type: 'n',   meaning: 'bác sĩ — người chữa bệnh' },
      { index: 62, word: 'nurse',       ipa: '/nɜːrs/',            type: 'n',   meaning: 'y tá — người chăm sóc bệnh nhân' },
      { index: 63, word: 'teacher',     ipa: '/ˈtiːtʃər/',         type: 'n',   meaning: 'giáo viên — người dạy học' },
      { index: 64, word: 'engineer',    ipa: '/ˌendʒɪˈnɪr/',       type: 'n',   meaning: 'kỹ sư' },
      { index: 65, word: 'lawyer',      ipa: '/ˈlɔːjər/',          type: 'n',   meaning: 'luật sư' },
      { index: 66, word: 'chef',        ipa: '/ʃef/',              type: 'n',   meaning: 'đầu bếp' },
      { index: 67, word: 'pilot',       ipa: '/ˈpaɪlət/',          type: 'n',   meaning: 'phi công' },
      { index: 68, word: 'dentist',     ipa: '/ˈdentɪst/',         type: 'n',   meaning: 'nha sĩ' },
      { index: 69, word: 'artist',      ipa: '/ˈɑːrtɪst/',         type: 'n',   meaning: 'họa sĩ / nghệ sĩ' },
      { index: 70, word: 'singer',      ipa: '/ˈsɪŋər/',           type: 'n',   meaning: 'ca sĩ' },
      { index: 71, word: 'accountant', ipa: '/əˈkaʊntənt/',       type: 'n',   meaning: 'kế toán' },
      { index: 72, word: 'architect',  ipa: '/ˈɑːrkɪtekt/',       type: 'n',   meaning: 'kiến trúc sư' },
    ],
  },
  {
    id: 7,
    name: 'Gia đình',
    words: [
      { index: 73, word: 'mother',      ipa: '/ˈmʌðər/',           type: 'n',   meaning: 'mẹ' },
      { index: 74, word: 'father',      ipa: '/ˈfɑːðər/',          type: 'n',   meaning: 'bố' },
      { index: 75, word: 'sister',      ipa: '/ˈsɪstər/',          type: 'n',   meaning: 'chị / em gái' },
      { index: 76, word: 'brother',     ipa: '/ˈbrʌðər/',          type: 'n',   meaning: 'anh / em trai' },
      { index: 77, word: 'grandmother', ipa: '/ˈɡrænmʌðər/',       type: 'n',   meaning: 'bà' },
      { index: 78, word: 'grandfather', ipa: '/ˈɡrænfɑːðər/',      type: 'n',   meaning: 'ông' },
      { index: 79, word: 'daughter',    ipa: '/ˈdɔːtər/',          type: 'n',   meaning: 'con gái' },
      { index: 80, word: 'son',         ipa: '/sʌn/',              type: 'n',   meaning: 'con trai' },
      { index: 81, word: 'aunt',        ipa: '/ænt/',              type: 'n',   meaning: 'cô / dì' },
      { index: 82, word: 'uncle',       ipa: '/ˈʌŋkl/',            type: 'n',   meaning: 'chú / bác / cậu' },
      { index: 83, word: 'husband',     ipa: '/ˈhʌzbənd/',         type: 'n',   meaning: 'chồng' },
      { index: 84, word: 'wife',        ipa: '/waɪf/',             type: 'n',   meaning: 'vợ' },
    ],
  },
  {
    id: 8,
    name: 'Đồ ăn & Thức uống',
    words: [
      { index: 85,  word: 'rice',       ipa: '/raɪs/',             type: 'n',   meaning: 'cơm / gạo' },
      { index: 86,  word: 'bread',      ipa: '/bred/',             type: 'n',   meaning: 'bánh mì' },
      { index: 87,  word: 'egg',        ipa: '/eɡ/',               type: 'n',   meaning: 'trứng' },
      { index: 88,  word: 'chicken',    ipa: '/ˈtʃɪkɪn/',          type: 'n',   meaning: 'thịt gà' },
      { index: 89,  word: 'fish',       ipa: '/fɪʃ/',              type: 'n',   meaning: 'cá' },
      { index: 90,  word: 'vegetable',  ipa: '/ˈvedʒtəbl/',        type: 'n',   meaning: 'rau củ' },
      { index: 91,  word: 'fruit',      ipa: '/fruːt/',            type: 'n',   meaning: 'trái cây' },
      { index: 92,  word: 'coffee',     ipa: '/ˈkɔːfi/',           type: 'n',   meaning: 'cà phê' },
      { index: 93,  word: 'tea',        ipa: '/tiː/',              type: 'n',   meaning: 'trà' },
      { index: 94,  word: 'milk',       ipa: '/mɪlk/',             type: 'n',   meaning: 'sữa' },
      { index: 95,  word: 'cake',       ipa: '/keɪk/',             type: 'n',   meaning: 'bánh ngọt' },
      { index: 96,  word: 'delicious',  ipa: '/dɪˈlɪʃəs/',         type: 'adj', meaning: 'ngon, ngon miệng' },
    ],
  },
  {
    id: 9,
    name: 'Màu sắc',
    words: [
      { index: 97,  word: 'red',        ipa: '/red/',              type: 'adj', meaning: 'màu đỏ' },
      { index: 98,  word: 'pink',       ipa: '/pɪŋk/',             type: 'adj', meaning: 'màu hồng' },
      { index: 99,  word: 'blue',       ipa: '/bluː/',             type: 'adj', meaning: 'màu xanh dương' },
      { index: 100, word: 'green',      ipa: '/ɡriːn/',            type: 'adj', meaning: 'màu xanh lá' },
      { index: 101, word: 'yellow',     ipa: '/ˈjeloʊ/',           type: 'adj', meaning: 'màu vàng' },
      { index: 102, word: 'purple',     ipa: '/ˈpɜːrpl/',          type: 'adj', meaning: 'màu tím' },
      { index: 103, word: 'orange',     ipa: '/ˈɔːrɪndʒ/',         type: 'adj', meaning: 'màu cam' },
      { index: 104, word: 'white',      ipa: '/waɪt/',             type: 'adj', meaning: 'màu trắng' },
      { index: 105, word: 'black',      ipa: '/blæk/',             type: 'adj', meaning: 'màu đen' },
      { index: 106, word: 'brown',      ipa: '/braʊn/',            type: 'adj', meaning: 'màu nâu' },
      { index: 107, word: 'gray',       ipa: '/ɡreɪ/',             type: 'adj', meaning: 'màu xám' },
      { index: 108, word: 'golden',     ipa: '/ˈɡoʊldən/',         type: 'adj', meaning: 'màu vàng kim' },
    ],
  },
  {
    id: 10,
    name: 'Động vật',
    words: [
      { index: 109, word: 'cat',        ipa: '/kæt/',              type: 'n',   meaning: 'con mèo' },
      { index: 110, word: 'dog',        ipa: '/dɔːɡ/',             type: 'n',   meaning: 'con chó' },
      { index: 111, word: 'rabbit',     ipa: '/ˈræbɪt/',           type: 'n',   meaning: 'con thỏ' },
      { index: 112, word: 'bird',       ipa: '/bɜːrd/',            type: 'n',   meaning: 'con chim' },
      { index: 113, word: 'butterfly',  ipa: '/ˈbʌtərflaɪ/',       type: 'n',   meaning: 'con bướm' },
      { index: 114, word: 'horse',      ipa: '/hɔːrs/',            type: 'n',   meaning: 'con ngựa' },
      { index: 115, word: 'elephant',   ipa: '/ˈelɪfənt/',         type: 'n',   meaning: 'con voi' },
      { index: 116, word: 'lion',       ipa: '/ˈlaɪən/',           type: 'n',   meaning: 'sư tử' },
      { index: 117, word: 'tiger',      ipa: '/ˈtaɪɡər/',          type: 'n',   meaning: 'con hổ' },
      { index: 118, word: 'monkey',     ipa: '/ˈmʌŋki/',           type: 'n',   meaning: 'con khỉ' },
      { index: 119, word: 'dolphin',    ipa: '/ˈdɑːlfɪn/',         type: 'n',   meaning: 'cá heo' },
      { index: 120, word: 'unicorn',    ipa: '/ˈjuːnɪkɔːrn/',      type: 'n',   meaning: 'kỳ lân 🦄' },
    ],
  },
  {
    id: 11,
    name: 'Cảm xúc',
    words: [
      { index: 121, word: 'happy',      ipa: '/ˈhæpi/',            type: 'adj', meaning: 'vui vẻ, hạnh phúc' },
      { index: 122, word: 'sad',        ipa: '/sæd/',              type: 'adj', meaning: 'buồn' },
      { index: 123, word: 'angry',      ipa: '/ˈæŋɡri/',           type: 'adj', meaning: 'tức giận' },
      { index: 124, word: 'excited',    ipa: '/ɪkˈsaɪtɪd/',        type: 'adj', meaning: 'phấn khích, hào hứng' },
      { index: 125, word: 'tired',      ipa: '/ˈtaɪərd/',          type: 'adj', meaning: 'mệt mỏi' },
      { index: 126, word: 'scared',     ipa: '/skerd/',            type: 'adj', meaning: 'sợ hãi' },
      { index: 127, word: 'surprised',  ipa: '/sərˈpraɪzd/',       type: 'adj', meaning: 'ngạc nhiên' },
      { index: 128, word: 'nervous',    ipa: '/ˈnɜːrvəs/',         type: 'adj', meaning: 'lo lắng, hồi hộp' },
      { index: 129, word: 'proud',      ipa: '/praʊd/',            type: 'adj', meaning: 'tự hào' },
      { index: 130, word: 'shy',        ipa: '/ʃaɪ/',              type: 'adj', meaning: 'nhút nhát, ngại ngùng' },
      { index: 131, word: 'calm',       ipa: '/kɑːm/',             type: 'adj', meaning: 'bình tĩnh' },
      { index: 132, word: 'smile',      ipa: '/smaɪl/',            type: 'v',   meaning: 'mỉm cười' },
    ],
  },
  {
    id: 12,
    name: 'Du lịch',
    words: [
      { index: 133, word: 'airport',    ipa: '/ˈerpɔːrt/',         type: 'n',   meaning: 'sân bay' },
      { index: 134, word: 'ticket',     ipa: '/ˈtɪkɪt/',           type: 'n',   meaning: 'vé' },
      { index: 135, word: 'passport',   ipa: '/ˈpæspɔːrt/',        type: 'n',   meaning: 'hộ chiếu' },
      { index: 136, word: 'luggage',    ipa: '/ˈlʌɡɪdʒ/',          type: 'n',   meaning: 'hành lý' },
      { index: 137, word: 'hotel',      ipa: '/hoʊˈtel/',          type: 'n',   meaning: 'khách sạn' },
      { index: 138, word: 'beach',      ipa: '/biːtʃ/',            type: 'n',   meaning: 'bãi biển' },
      { index: 139, word: 'map',        ipa: '/mæp/',              type: 'n',   meaning: 'bản đồ' },
      { index: 140, word: 'flight',     ipa: '/flaɪt/',            type: 'n',   meaning: 'chuyến bay' },
      { index: 141, word: 'tourist',    ipa: '/ˈtʊrɪst/',          type: 'n',   meaning: 'khách du lịch' },
      { index: 142, word: 'journey',    ipa: '/ˈdʒɜːrni/',         type: 'n',   meaning: 'hành trình' },
      { index: 143, word: 'explore',    ipa: '/ɪkˈsplɔːr/',        type: 'v',   meaning: 'khám phá' },
      { index: 144, word: 'depart',     ipa: '/dɪˈpɑːrt/',         type: 'v',   meaning: 'khởi hành' },
    ],
  },
  {
    id: 13,
    name: 'Tình yêu 💕',
    words: [
      { index: 145, word: 'love',       ipa: '/lʌv/',              type: 'v',   meaning: 'yêu, tình yêu' },
      { index: 146, word: 'heart',      ipa: '/hɑːrt/',            type: 'n',   meaning: 'trái tim' },
      { index: 147, word: 'kiss',       ipa: '/kɪs/',              type: 'n',   meaning: 'nụ hôn' },
      { index: 148, word: 'hug',        ipa: '/hʌɡ/',              type: 'n',   meaning: 'cái ôm' },
      { index: 149, word: 'sweetheart', ipa: '/ˈswiːthɑːrt/',      type: 'n',   meaning: 'người yêu, cưng' },
      { index: 150, word: 'darling',    ipa: '/ˈdɑːrlɪŋ/',         type: 'n',   meaning: 'em yêu, cưng' },
      { index: 151, word: 'romantic',   ipa: '/roʊˈmæntɪk/',       type: 'adj', meaning: 'lãng mạn' },
      { index: 152, word: 'beautiful',  ipa: '/ˈbjuːtɪfl/',        type: 'adj', meaning: 'xinh đẹp' },
      { index: 153, word: 'adorable',   ipa: '/əˈdɔːrəbl/',        type: 'adj', meaning: 'đáng yêu' },
      { index: 154, word: 'forever',    ipa: '/fərˈevər/',         type: 'adv', meaning: 'mãi mãi' },
      { index: 155, word: 'miss',       ipa: '/mɪs/',              type: 'v',   meaning: 'nhớ (ai đó)' },
      { index: 156, word: 'promise',    ipa: '/ˈprɑːmɪs/',         type: 'v',   meaning: 'hứa, lời hứa' },
    ],
  },
  {
    id: 14,
    name: 'Thời tiết',
    words: [
      { index: 157, word: 'sunny',      ipa: '/ˈsʌni/',            type: 'adj', meaning: 'nắng' },
      { index: 158, word: 'rainy',      ipa: '/ˈreɪni/',           type: 'adj', meaning: 'mưa' },
      { index: 159, word: 'cloudy',     ipa: '/ˈklaʊdi/',          type: 'adj', meaning: 'nhiều mây' },
      { index: 160, word: 'windy',      ipa: '/ˈwɪndi/',           type: 'adj', meaning: 'có gió' },
      { index: 161, word: 'snow',       ipa: '/snoʊ/',             type: 'n',   meaning: 'tuyết' },
      { index: 162, word: 'storm',      ipa: '/stɔːrm/',           type: 'n',   meaning: 'bão' },
      { index: 163, word: 'rainbow',    ipa: '/ˈreɪnboʊ/',         type: 'n',   meaning: 'cầu vồng' },
      { index: 164, word: 'hot',        ipa: '/hɑːt/',             type: 'adj', meaning: 'nóng' },
      { index: 165, word: 'cold',       ipa: '/koʊld/',            type: 'adj', meaning: 'lạnh' },
      { index: 166, word: 'warm',       ipa: '/wɔːrm/',            type: 'adj', meaning: 'ấm áp' },
      { index: 167, word: 'fog',        ipa: '/fɔːɡ/',             type: 'n',   meaning: 'sương mù' },
      { index: 168, word: 'thunder',    ipa: '/ˈθʌndər/',          type: 'n',   meaning: 'sấm' },
    ],
  },
  {
    id: 15,
    name: 'Trang phục 👗',
    words: [
      { index: 169, word: 'dress',      ipa: '/dres/',             type: 'n',   meaning: 'váy đầm' },
      { index: 170, word: 'skirt',      ipa: '/skɜːrt/',           type: 'n',   meaning: 'chân váy' },
      { index: 171, word: 'shirt',      ipa: '/ʃɜːrt/',            type: 'n',   meaning: 'áo sơ mi' },
      { index: 172, word: 'shoes',      ipa: '/ʃuːz/',             type: 'n',   meaning: 'giày' },
      { index: 173, word: 'hat',        ipa: '/hæt/',              type: 'n',   meaning: 'mũ' },
      { index: 174, word: 'coat',       ipa: '/koʊt/',             type: 'n',   meaning: 'áo khoác' },
      { index: 175, word: 'gloves',     ipa: '/ɡlʌvz/',            type: 'n',   meaning: 'găng tay' },
      { index: 176, word: 'scarf',      ipa: '/skɑːrf/',           type: 'n',   meaning: 'khăn quàng cổ' },
      { index: 177, word: 'ring',       ipa: '/rɪŋ/',              type: 'n',   meaning: 'nhẫn' },
      { index: 178, word: 'gown',       ipa: '/ɡaʊn/',             type: 'n',   meaning: 'váy dạ hội' },
      { index: 179, word: 'crown',      ipa: '/kraʊn/',            type: 'n',   meaning: 'vương miện 👑' },
      { index: 180, word: 'princess',   ipa: '/ˈprɪnses/',         type: 'n',   meaning: 'công chúa 👸' },
    ],
  },
  {
    id: 16,
    name: 'Office Technology',
    words: [
      { index: 181, word: 'device',      ipa: '/dɪˈvaɪs/',         type: 'n',   meaning: 'thiết bị' },
      { index: 182, word: 'equipment',   ipa: '/ɪˈkwɪpmənt/',      type: 'n',   meaning: 'trang thiết bị' },
      { index: 183, word: 'printer',     ipa: '/ˈprɪntər/',        type: 'n',   meaning: 'máy in' },
      { index: 184, word: 'keyboard',    ipa: '/ˈkiːbɔːrd/',       type: 'n',   meaning: 'bàn phím' },
      { index: 185, word: 'software',    ipa: '/ˈsɔːftwer/',       type: 'n',   meaning: 'phần mềm' },
      { index: 186, word: 'install',     ipa: '/ɪnˈstɔːl/',        type: 'v',   meaning: 'cài đặt' },
      { index: 187, word: 'upgrade',     ipa: '/ˈʌpɡreɪd/',        type: 'v',   meaning: 'nâng cấp' },
      { index: 188, word: 'operate',     ipa: '/ˈɑːpəreɪt/',       type: 'v',   meaning: 'vận hành' },
      { index: 189, word: 'efficient',   ipa: '/ɪˈfɪʃnt/',         type: 'adj', meaning: 'hiệu quả' },
      { index: 190, word: 'reliable',    ipa: '/rɪˈlaɪəbl/',       type: 'adj', meaning: 'đáng tin cậy' },
      { index: 191, word: 'automatic',   ipa: '/ˌɔːtəˈmætɪk/',     type: 'adj', meaning: 'tự động' },
      { index: 192, word: 'malfunction', ipa: '/ˌmælˈfʌŋkʃn/',     type: 'n',   meaning: 'sự trục trặc, hỏng hóc' },
    ],
  },
  {
    id: 17,
    name: 'Recruitment & Hiring',
    words: [
      { index: 193, word: 'candidate',     ipa: '/ˈkændɪdət/',        type: 'n',   meaning: 'ứng viên' },
      { index: 194, word: 'applicant',     ipa: '/ˈæplɪkənt/',        type: 'n',   meaning: 'người nộp đơn' },
      { index: 195, word: 'resume',        ipa: '/ˈrezəmeɪ/',         type: 'n',   meaning: 'sơ yếu lý lịch (CV)' },
      { index: 196, word: 'interview',     ipa: '/ˈɪntərvjuː/',       type: 'n',   meaning: 'buổi phỏng vấn' },
      { index: 197, word: 'qualification', ipa: '/ˌkwɑːlɪfɪˈkeɪʃn/',  type: 'n',   meaning: 'bằng cấp, trình độ' },
      { index: 198, word: 'position',      ipa: '/pəˈzɪʃn/',          type: 'n',   meaning: 'vị trí công việc' },
      { index: 199, word: 'recruit',       ipa: '/rɪˈkruːt/',         type: 'v',   meaning: 'tuyển dụng' },
      { index: 200, word: 'hire',          ipa: '/ˈhaɪər/',           type: 'v',   meaning: 'thuê, tuyển' },
      { index: 201, word: 'apply',         ipa: '/əˈplaɪ/',           type: 'v',   meaning: 'nộp đơn, ứng tuyển' },
      { index: 202, word: 'qualified',     ipa: '/ˈkwɑːlɪfaɪd/',      type: 'adj', meaning: 'đủ điều kiện, có năng lực' },
      { index: 203, word: 'experienced',   ipa: '/ɪkˈspɪriənst/',     type: 'adj', meaning: 'có kinh nghiệm' },
      { index: 204, word: 'vacancy',       ipa: '/ˈveɪkənsi/',        type: 'n',   meaning: 'vị trí còn trống' },
    ],
  },
  {
    id: 18,
    name: 'Salaries & Benefits',
    words: [
      { index: 205, word: 'salary',       ipa: '/ˈsæləri/',          type: 'n',   meaning: 'lương' },
      { index: 206, word: 'wage',         ipa: '/weɪdʒ/',            type: 'n',   meaning: 'tiền công' },
      { index: 207, word: 'bonus',        ipa: '/ˈboʊnəs/',          type: 'n',   meaning: 'tiền thưởng' },
      { index: 208, word: 'benefit',      ipa: '/ˈbenɪfɪt/',         type: 'n',   meaning: 'phúc lợi' },
      { index: 209, word: 'raise',        ipa: '/reɪz/',             type: 'n',   meaning: 'sự tăng lương' },
      { index: 210, word: 'compensation', ipa: '/ˌkɑːmpenˈseɪʃn/',   type: 'n',   meaning: 'khoản đãi ngộ, đền bù' },
      { index: 211, word: 'pension',      ipa: '/ˈpenʃn/',           type: 'n',   meaning: 'lương hưu' },
      { index: 212, word: 'negotiate',    ipa: '/nɪˈɡoʊʃieɪt/',      type: 'v',   meaning: 'đàm phán, thương lượng' },
      { index: 213, word: 'earn',         ipa: '/ɜːrn/',             type: 'v',   meaning: 'kiếm (tiền)' },
      { index: 214, word: 'deserve',      ipa: '/dɪˈzɜːrv/',         type: 'v',   meaning: 'xứng đáng' },
      { index: 215, word: 'competitive',  ipa: '/kəmˈpetətɪv/',      type: 'adj', meaning: 'cạnh tranh, hấp dẫn' },
      { index: 216, word: 'generous',     ipa: '/ˈdʒenərəs/',        type: 'adj', meaning: 'hào phóng' },
    ],
  },
  {
    id: 19,
    name: 'Shopping & Ordering',
    words: [
      { index: 217, word: 'order',       ipa: '/ˈɔːrdər/',          type: 'n',   meaning: 'đơn đặt hàng' },
      { index: 218, word: 'product',     ipa: '/ˈprɑːdʌkt/',        type: 'n',   meaning: 'sản phẩm' },
      { index: 219, word: 'discount',    ipa: '/ˈdɪskaʊnt/',        type: 'n',   meaning: 'chiết khấu, giảm giá' },
      { index: 220, word: 'receipt',     ipa: '/rɪˈsiːt/',          type: 'n',   meaning: 'biên lai' },
      { index: 221, word: 'merchandise', ipa: '/ˈmɜːrtʃəndaɪs/',    type: 'n',   meaning: 'hàng hóa' },
      { index: 222, word: 'warehouse',   ipa: '/ˈwerhaʊs/',         type: 'n',   meaning: 'kho hàng' },
      { index: 223, word: 'purchase',    ipa: '/ˈpɜːrtʃəs/',        type: 'v',   meaning: 'mua' },
      { index: 224, word: 'select',      ipa: '/sɪˈlekt/',          type: 'v',   meaning: 'lựa chọn' },
      { index: 225, word: 'deliver',     ipa: '/dɪˈlɪvər/',         type: 'v',   meaning: 'giao hàng' },
      { index: 226, word: 'affordable',  ipa: '/əˈfɔːrdəbl/',       type: 'adj', meaning: 'phải chăng' },
      { index: 227, word: 'available',   ipa: '/əˈveɪləbl/',        type: 'adj', meaning: 'có sẵn' },
      { index: 228, word: 'in stock',    ipa: '/ɪn stɑːk/',         type: 'adj', meaning: 'còn hàng' },
    ],
  },
  {
    id: 20,
    name: 'Shipping & Invoices',
    words: [
      { index: 229, word: 'shipment', ipa: '/ˈʃɪpmənt/',         type: 'n',   meaning: 'lô hàng' },
      { index: 230, word: 'invoice',  ipa: '/ˈɪnvɔɪs/',          type: 'n',   meaning: 'hóa đơn' },
      { index: 231, word: 'package',  ipa: '/ˈpækɪdʒ/',          type: 'n',   meaning: 'kiện hàng' },
      { index: 232, word: 'delivery', ipa: '/dɪˈlɪvəri/',        type: 'n',   meaning: 'sự giao hàng' },
      { index: 233, word: 'freight',  ipa: '/freɪt/',            type: 'n',   meaning: 'hàng hóa vận chuyển' },
      { index: 234, word: 'carrier',  ipa: '/ˈkæriər/',          type: 'n',   meaning: 'hãng vận chuyển' },
      { index: 235, word: 'estimate', ipa: '/ˈestɪmət/',         type: 'n',   meaning: 'bản ước tính' },
      { index: 236, word: 'dispatch', ipa: '/dɪˈspætʃ/',         type: 'v',   meaning: 'gửi đi' },
      { index: 237, word: 'track',    ipa: '/træk/',             type: 'v',   meaning: 'theo dõi (đơn hàng)' },
      { index: 238, word: 'fragile',  ipa: '/ˈfrædʒl/',          type: 'adj', meaning: 'dễ vỡ' },
      { index: 239, word: 'overdue',  ipa: '/ˌoʊvərˈduː/',       type: 'adj', meaning: 'quá hạn' },
      { index: 240, word: 'prompt',   ipa: '/prɑːmpt/',          type: 'adj', meaning: 'kịp thời, đúng hẹn' },
    ],
  },
  {
    id: 21,
    name: 'Banking & Finance',
    words: [
      { index: 241, word: 'account',   ipa: '/əˈkaʊnt/',          type: 'n',   meaning: 'tài khoản' },
      { index: 242, word: 'deposit',   ipa: '/dɪˈpɑːzɪt/',        type: 'n',   meaning: 'khoản tiền gửi' },
      { index: 243, word: 'loan',      ipa: '/loʊn/',             type: 'n',   meaning: 'khoản vay' },
      { index: 244, word: 'interest',  ipa: '/ˈɪntrəst/',         type: 'n',   meaning: 'lãi suất' },
      { index: 245, word: 'balance',   ipa: '/ˈbæləns/',          type: 'n',   meaning: 'số dư' },
      { index: 246, word: 'budget',    ipa: '/ˈbʌdʒɪt/',          type: 'n',   meaning: 'ngân sách' },
      { index: 247, word: 'profit',    ipa: '/ˈprɑːfɪt/',         type: 'n',   meaning: 'lợi nhuận' },
      { index: 248, word: 'expense',   ipa: '/ɪkˈspens/',         type: 'n',   meaning: 'chi phí' },
      { index: 249, word: 'withdraw',  ipa: '/wɪðˈdrɔː/',         type: 'v',   meaning: 'rút (tiền)' },
      { index: 250, word: 'transfer',  ipa: '/trænsˈfɜːr/',       type: 'v',   meaning: 'chuyển khoản' },
      { index: 251, word: 'invest',    ipa: '/ɪnˈvest/',          type: 'v',   meaning: 'đầu tư' },
      { index: 252, word: 'financial', ipa: '/faɪˈnænʃl/',        type: 'adj', meaning: 'thuộc tài chính' },
    ],
  },
  {
    id: 22,
    name: 'Restaurants & Dining',
    words: [
      { index: 253, word: 'reservation', ipa: '/ˌrezərˈveɪʃn/',     type: 'n',   meaning: 'sự đặt chỗ' },
      { index: 254, word: 'menu',        ipa: '/ˈmenjuː/',          type: 'n',   meaning: 'thực đơn' },
      { index: 255, word: 'waiter',      ipa: '/ˈweɪtər/',          type: 'n',   meaning: 'phục vụ bàn' },
      { index: 256, word: 'bill',        ipa: '/bɪl/',              type: 'n',   meaning: 'hóa đơn thanh toán' },
      { index: 257, word: 'tip',         ipa: '/tɪp/',              type: 'n',   meaning: 'tiền boa' },
      { index: 258, word: 'cuisine',     ipa: '/kwɪˈziːn/',         type: 'n',   meaning: 'ẩm thực' },
      { index: 259, word: 'beverage',    ipa: '/ˈbevərɪdʒ/',        type: 'n',   meaning: 'đồ uống' },
      { index: 260, word: 'reserve',     ipa: '/rɪˈzɜːrv/',         type: 'v',   meaning: 'đặt trước' },
      { index: 261, word: 'serve',       ipa: '/sɜːrv/',            type: 'v',   meaning: 'phục vụ' },
      { index: 262, word: 'recommend',   ipa: '/ˌrekəˈmend/',       type: 'v',   meaning: 'gợi ý, đề xuất' },
      { index: 263, word: 'tasty',       ipa: '/ˈteɪsti/',          type: 'adj', meaning: 'ngon miệng' },
      { index: 264, word: 'popular',     ipa: '/ˈpɑːpjələr/',       type: 'adj', meaning: 'phổ biến, được ưa chuộng' },
    ],
  },
  {
    id: 23,
    name: 'Hotels & Business Travel',
    words: [
      { index: 265, word: 'check-in',      ipa: '/ˈtʃek ɪn/',         type: 'n',   meaning: 'thủ tục nhận phòng' },
      { index: 266, word: 'lobby',         ipa: '/ˈlɑːbi/',           type: 'n',   meaning: 'sảnh khách sạn' },
      { index: 267, word: 'suite',         ipa: '/swiːt/',            type: 'n',   meaning: 'phòng hạng sang' },
      { index: 268, word: 'receptionist',  ipa: '/rɪˈsepʃənɪst/',     type: 'n',   meaning: 'lễ tân' },
      { index: 269, word: 'amenity',       ipa: '/əˈmiːnəti/',        type: 'n',   meaning: 'tiện nghi' },
      { index: 270, word: 'accommodation', ipa: '/əˌkɑːməˈdeɪʃn/',    type: 'n',   meaning: 'chỗ ở' },
      { index: 271, word: 'book',          ipa: '/bʊk/',              type: 'v',   meaning: 'đặt (phòng)' },
      { index: 272, word: 'confirm',       ipa: '/kənˈfɜːrm/',        type: 'v',   meaning: 'xác nhận' },
      { index: 273, word: 'check out',     ipa: '/ˌtʃekˈaʊt/',        type: 'v',   meaning: 'trả phòng' },
      { index: 274, word: 'spacious',      ipa: '/ˈspeɪʃəs/',         type: 'adj', meaning: 'rộng rãi' },
      { index: 275, word: 'comfortable',   ipa: '/ˈkʌmftəbl/',        type: 'adj', meaning: 'thoải mái' },
      { index: 276, word: 'complimentary', ipa: '/ˌkɑːmplɪˈmentri/',  type: 'adj', meaning: 'miễn phí kèm theo' },
    ],
  },
];

// Phân nhóm chủ đề: TOEIC (ôn thi) và Đời sống (giao tiếp hằng ngày)
const TOEIC_TOPIC_IDS = new Set([1, 2, 3, 4, 5, 16, 17, 18, 19, 20, 21, 22, 23]);
TOPICS.forEach(t => {
  t.group = TOEIC_TOPIC_IDS.has(t.id) ? 'TOEIC' : 'Đời sống';
});

// Flat array of all words across all topics — used by the Random Quiz feature
const ALL_WORDS = TOPICS.flatMap(t => t.words);
