// Vocabulary data — 5 TOEIC topics parsed from 5.topic.txt
const TOPICS = [
  {
    id: 1,
    name: 'Contracts',
    words: [
      { index: 1,  word: 'agreement',   ipa: '/əˈɡriːmənt/',      type: 'n',   meaning: 'một thỏa thuận chung, một hợp đồng' },
      { index: 2,  word: 'party',       ipa: '/ˈpɑːrti/',          type: 'n',   meaning: 'một người hoặc một nhóm tham gia vào một hợp đồng' },
      { index: 3,  word: 'provision',   ipa: '/prəˈvɪʒn/',         type: 'n',   meaning: 'một điều kiện cụ thể trong hợp đồng' },
      { index: 4,  word: 'clause',      ipa: '/klɔːz/',            type: 'n',   meaning: 'một phần trong hợp đồng' },
      { index: 5,  word: 'agree',       ipa: '/əˈɡriː/',           type: 'v',   meaning: 'có cùng quan điểm hoặc sự hiểu biết' },
      { index: 6,  word: 'obligate',    ipa: '/ˈɑːblɪɡeɪt/',      type: 'v',   meaning: 'ràng buộc về mặt pháp lý hoặc đạo đức' },
      { index: 7,  word: 'sign',        ipa: '/saɪn/',             type: 'v',   meaning: 'viết tên của bạn vào một tài liệu để thể hiện sự chấp thuận' },
      { index: 8,  word: 'resolve',     ipa: '/rɪˈzɑːlv/',        type: 'v',   meaning: 'để tìm một giải pháp' },
      { index: 9,  word: 'binding',     ipa: '/ˈbaɪndɪŋ/',        type: 'adj', meaning: 'yêu cầu về mặt pháp lý' },
      { index: 10, word: 'contractual', ipa: '/kənˈtræktʃuəl/',   type: 'adj', meaning: 'liên quan đến hợp đồng' },
      { index: 11, word: 'legal',       ipa: '/ˈliːɡl/',           type: 'adj', meaning: 'được pháp luật cho phép' },
      { index: 12, word: 'legally',     ipa: '/ˈliːɡəli/',         type: 'adv', meaning: 'theo cách được pháp luật cho phép' },
    ],
  },
  {
    id: 2,
    name: 'Marketing',
    words: [
      { index: 13, word: 'market',      ipa: '/ˈmɑːrkɪt/',        type: 'n',   meaning: 'nhu cầu về một sản phẩm' },
      { index: 14, word: 'competition', ipa: '/ˌkɑːmpəˈtɪʃn/',   type: 'n',   meaning: 'hoạt động cạnh tranh' },
      { index: 15, word: 'strategy',    ipa: '/ˈstrætədʒi/',      type: 'n',   meaning: 'một kế hoạch hành động' },
      { index: 16, word: 'customer',    ipa: '/ˈkʌstəmər/',       type: 'n',   meaning: 'ai đó mua hàng hóa hoặc dịch vụ' },
      { index: 17, word: 'advertise',   ipa: '/ˈædvərtaɪz/',      type: 'v',   meaning: 'để quảng bá một sản phẩm hoặc dịch vụ' },
      { index: 18, word: 'attract',     ipa: '/əˈtrækt/',          type: 'v',   meaning: 'để rút ra bằng cách kháng cáo' },
      { index: 19, word: 'consume',     ipa: '/kənˈsuːm/',         type: 'v',   meaning: 'sử dụng hoặc mua một sản phẩm' },
      { index: 20, word: 'promote',     ipa: '/prəˈmoʊt/',         type: 'v',   meaning: 'để quảng bá và bán' },
      { index: 21, word: 'effective',   ipa: '/ɪˈfɛktɪv/',        type: 'adj', meaning: 'thành công trong việc tạo ra một kết quả mong muốn' },
      { index: 22, word: 'productive',  ipa: '/prəˈdʌktɪv/',      type: 'adj', meaning: 'có thể sản xuất số lượng lớn' },
      { index: 23, word: 'persuasive',  ipa: '/pərˈsweɪsɪv/',     type: 'adj', meaning: 'giỏi thuyết phục người khác' },
      { index: 24, word: 'efficiently', ipa: '/ɪˈfɪʃəntli/',      type: 'adv', meaning: 'theo cách đạt được năng suất tối đa' },
    ],
  },
  {
    id: 3,
    name: 'Warranties',
    words: [
      { index: 25, word: 'warranty',    ipa: '/ˈwɔːrənti/',       type: 'n',   meaning: 'một sự đảm bảo' },
      { index: 26, word: 'defect',      ipa: '/ˈdiːfɛkt/',        type: 'n',   meaning: 'một lỗi hoặc sự không hoàn hảo' },
      { index: 27, word: 'claim',       ipa: '/kleɪm/',            type: 'n',   meaning: 'một nhu cầu cho một cái gì đó do' },
      { index: 28, word: 'coverage',    ipa: '/ˈkʌvərɪdʒ/',       type: 'n',   meaning: 'mức độ mà một cái gì đó được bảo hiểm' },
      { index: 29, word: 'guarantee',   ipa: '/ˌɡærənˈtiː/',      type: 'v',   meaning: 'cam kết về chất lượng sản phẩm' },
      { index: 30, word: 'replace',     ipa: '/rɪˈpleɪs/',        type: 'v',   meaning: 'thay thế' },
      { index: 31, word: 'refund',      ipa: '/ˈriːfʌnd/',        type: 'v',   meaning: 'trả lại tiền' },
      { index: 32, word: 'repair',      ipa: '/rɪˈpɛr/',          type: 'v',   meaning: 'để sửa chữa hoặc khôi phục' },
      { index: 33, word: 'defective',   ipa: '/dɪˈfɛktɪv/',      type: 'adj', meaning: 'có lỗi' },
      { index: 34, word: 'valid',       ipa: '/ˈvælɪd/',          type: 'adj', meaning: 'được chấp nhận về mặt pháp lý' },
      { index: 35, word: 'expired',     ipa: '/ɪkˈspaɪərd/',      type: 'adj', meaning: 'không còn hiệu lực' },
      { index: 36, word: 'promptly',    ipa: '/ˈprɑːmptli/',      type: 'adv', meaning: 'không chậm trễ' },
    ],
  },
  {
    id: 4,
    name: 'Business Planning',
    words: [
      { index: 37, word: 'goal',        ipa: '/ɡoʊl/',            type: 'n',   meaning: 'một mục tiêu hoặc kết quả mong muốn' },
      { index: 38, word: 'strategy',    ipa: '/ˈstrætədʒi/',      type: 'n',   meaning: 'một kế hoạch hành động' },
      { index: 39, word: 'forecast',    ipa: '/ˈfɔːrkæst/',       type: 'n',   meaning: 'một dự đoán' },
      { index: 40, word: 'resource',    ipa: '/ˈriːsɔːrs/',       type: 'n',   meaning: 'một cổ phiếu hoặc nguồn cung cấp' },
      { index: 41, word: 'predict',     ipa: '/prɪˈdɪkt/',        type: 'v',   meaning: 'để dự đoán tương lai' },
      { index: 42, word: 'plan',        ipa: '/plæn/',             type: 'v',   meaning: 'quyết định và sắp xếp' },
      { index: 43, word: 'analyze',     ipa: '/ˈænəlaɪz/',        type: 'v',   meaning: 'để kiểm tra chi tiết' },
      { index: 44, word: 'assess',      ipa: '/əˈsɛs/',           type: 'v',   meaning: 'để đánh giá hoặc ước tính' },
      { index: 45, word: 'strategic',   ipa: '/strəˈtiːdʒɪk/',   type: 'adj', meaning: 'liên quan đến kế hoạch dài hạn' },
      { index: 46, word: 'realistic',   ipa: '/ˌriːəˈlɪstɪk/',   type: 'adj', meaning: 'thực tế và có thể đạt được' },
      { index: 47, word: 'achievable',  ipa: '/əˈtʃiːvəbl/',     type: 'adj', meaning: 'có khả năng thực hiện được' },
      { index: 48, word: 'effectively', ipa: '/ɪˈfɛktɪvli/',     type: 'adv', meaning: 'theo cách đạt được kết quả mong muốn' },
    ],
  },
  {
    id: 5,
    name: 'Conferences',
    words: [
      { index: 49, word: 'attendee',     ipa: '/əˌtɛnˈdiː/',      type: 'n',   meaning: 'một người tham dự một cuộc họp' },
      { index: 50, word: 'schedule',     ipa: '/ˈskɛdʒuːl/',      type: 'n',   meaning: 'kế hoạch sự kiện' },
      { index: 51, word: 'location',     ipa: '/loʊˈkeɪʃn/',      type: 'n',   meaning: 'một địa điểm hoặc vị trí' },
      { index: 52, word: 'venue',        ipa: '/ˈvɛnjuː/',         type: 'n',   meaning: 'nơi diễn ra sự kiện' },
      { index: 53, word: 'arrange',      ipa: '/əˈreɪndʒ/',        type: 'v',   meaning: 'lập kế hoạch và tổ chức' },
      { index: 54, word: 'hold',         ipa: '/hoʊld/',           type: 'v',   meaning: 'tổ chức hoặc tiến hành' },
      { index: 55, word: 'participate',  ipa: '/pɑːrˈtɪsɪpeɪt/', type: 'v',   meaning: 'tham gia' },
      { index: 56, word: 'register',     ipa: '/ˈrɛdʒɪstər/',     type: 'v',   meaning: 'để ghi danh hoặc đăng ký' },
      { index: 57, word: 'convenient',   ipa: '/kənˈviːniənt/',   type: 'adj', meaning: 'phù hợp tốt với nhu cầu của một người' },
      { index: 58, word: 'scheduled',    ipa: '/ˈskɛdʒuːld/',     type: 'adj', meaning: 'lên kế hoạch hoặc sắp xếp cho' },
      { index: 59, word: 'confirmed',    ipa: '/kənˈfɜːrmd/',     type: 'adj', meaning: 'được thành lập hoặc xác minh' },
      { index: 60, word: 'international',ipa: '/ˌɪntəˈnæʃnəl/',  type: 'adj', meaning: 'quốc tế' },
    ],
  },
];

// Flat array of all words across all topics — used by the Random Quiz feature
const ALL_WORDS = TOPICS.flatMap(t => t.words);
